In [1]:
import numpy as np
import pandas as pd

In [2]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
type(a)

numpy.ndarray

In [4]:
np.shape(a)

(4,)

In [5]:
a[2]

3

In [7]:
b = np.array([[1,2], [3,4]])
b

array([[1, 2],
       [3, 4]])

In [8]:
np.shape(b)

(2, 2)

In [10]:
b[1,1]

4

In [11]:
c = np.ones((3,4))
c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
d = np.zeros((2,3))
d

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
e = np.full((2,3),5)
e

array([[5, 5, 5],
       [5, 5, 5]])

In [15]:
f = np.random.random((3,4))
f

array([[0.82177593, 0.46310734, 0.23859139, 0.91971683],
       [0.19231087, 0.2943463 , 0.31465013, 0.34408651],
       [0.4127426 , 0.97342952, 0.04574817, 0.20134609]])

In [16]:
h = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
h

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
i = h[:2,1:3]
i

array([[2, 3],
       [6, 7]])

In [18]:
h[0,2]

3

In [19]:
i[0,1]

3

In [20]:
i[0,1]=2020

In [21]:
h[0,2]

2020

In [22]:
h

array([[   1,    2, 2020,    4],
       [   5,    6,    7,    8],
       [   9,   10,   11,   12]])